#!/usr/bin/env bash
set -euo pipefail
root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd -P)"; renderer="$root/scripts/ops/render-slashing-db-rehearsal.py"; scratch="$(mktemp -d)"; trap 'rm -rf "$scratch"' EXIT
image='106760547719.dkr.ecr.ap-northeast-2.amazonaws.com/node-operator-baseline-validator-runtime-postgres@sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
PYTHONDONTWRITEBYTECODE=1 python3 "$renderer" --volume-id vol-0123456789abcdef0 --image "$image" --output "$scratch/render.json"
jq -e --arg image "$image" '[.items[] | .kind] == ["PersistentVolume","PersistentVolumeClaim","NetworkPolicy","Pod"] and .items[0].spec.persistentVolumeReclaimPolicy == "Retain" and .items[0].spec.csi.volumeHandle == "vol-0123456789abcdef0" and .items[0].spec.nodeAffinity.required.nodeSelectorTerms[0].matchExpressions[0].values == ["ap-northeast-2c"] and .items[2].spec.policyTypes == ["Ingress","Egress"] and .items[3].spec.automountServiceAccountToken == false and .items[3].spec.terminationGracePeriodSeconds == 60 and .items[3].spec.securityContext.fsGroupChangePolicy == "OnRootMismatch" and .items[3].spec.containers[0].image == $image and .items[3].spec.containers[0].resources.limits.memory == "1Gi" and .items[3].spec.initContainers[0].resources.requests.cpu == "100m" and .items[3].spec.volumes[1].emptyDir.sizeLimit == "64Mi" and .items[3].spec.containers[0].command == ["postgres","-D","/var/lib/postgresql/data/pgdata","-c","listen_addresses=","-c","unix_socket_directories=/var/run/postgresql"] and (.items[3].spec.initContainers[0].command[-1] | contains("PG_VERSION")) and (.items[3].spec.initContainers[0].command[-1] | contains("awk -F:"))' "$scratch/render.json" >/dev/null
for volume in vol-ABC bad vol-095adf3e093cb529e; do if python3 "$renderer" --volume-id "$volume" --image "$image" --output "$scratch/$volume" >/dev/null 2>&1; then exit 1; fi; done
for bad_image in "postgres:16" "999999999999.dkr.ecr.ap-northeast-2.amazonaws.com/postgres@sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"; do if python3 "$renderer" --volume-id vol-0123456789abcdef0 --image "$bad_image" --output "$scratch/bad-image" >/dev/null 2>&1; then exit 1; fi; done
if python3 "$renderer" --volume-id vol-0123456789abcdef0 --image "$image" --output relative.json >/dev/null 2>&1; then exit 1; fi
parse_state() { LC_ALL=C awk -F: '$1 ~ /^Database cluster state[[:space:]]*$/ {v=$2; sub(/^[[:space:]]*/, "", v); sub(/[[:space:]]*$/, "", v); print v; exit}'; }
[ "$(printf 'Database cluster state:               shut down\n' | parse_state)" = 'shut down' ]
[ "$(printf 'Database cluster state:               in production\n' | parse_state)" != 'shut down' ]
