apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: validator-hoodi-gp3-kms
  labels:
    app.kubernetes.io/part-of: hoodi-validator
    node-operator.io/encryption-policy: baseline-ebs-kms
provisioner: ebs.csi.aws.com
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp3
  encrypted: "true"
  kmsKeyId: alias/node-op-2609120620-baseline-ebs
