name: Mirror cert-manager Chart

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  mirror:
    name: Artifact Mirror
    runs-on: ubuntu-24.04
    environment: gitops-oci-mirror
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with: {persist-credentials: false}
      - uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
        with: {version: v3.17.3}
      - name: cert-manager Chart Integrity and Mirror
        env:
          AWS_REGION: ap-northeast-2
          ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
          AWS_ROLE_ARN: ${{ vars.GITOPS_OCI_MIRROR_ROLE_ARN }}
        run: bash scripts/release/mirror-cert-manager-chart.sh
